### ISSUE TITLE
plugin in an alpine-container

### ISSUE THREAD

**Issue by ChristianKniep** [chooban/s3-docker-volume-plugin#1]
Loving the prospect of this plugin.
I would like to use minio (https://github.com/qnib/docker-minio) as a backend and this plugin within a container - exposing the socket via TCP - to be able to have a persistent volume.

AFAI see, you are assuming to run alongside systemd. 

```
bash-4.3# s3-docker-volume
info: Attempting to listen...
error: uncaughtException: No or too many file descriptors received. date=Fri Sep 09 2016 16:51:05 GMT+0000 (UTC), pid=13, uid=0, gid=0, cwd=/, execPath=/usr/bin/node, version=v6.2.0, argv=[/usr/bin/node, /usr/bin/s3-docker-volume], rss=33927168, heapTotal=18870272, heapUsed=11344864, loadavg=[0.16552734375, 0.14306640625, 0.10107421875], uptime=78357
Error: No or too many file descriptors received.
    at Server.listen (/usr/lib/node_modules/s3-volume-plugin/node_modules/systemd/lib/systemd.js:12:19)
    at Object.<anonymous> (/usr/lib/node_modules/s3-volume-plugin/bin/www:11:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
```

Any chance I can just run the plugin itself?

Cheers
Christian

**Comment by chooban** [comment]
Sorry, I completely missed that you'd posted this. I must have notifications turned off. 

From memory, I think the systemd line was just to get it running as a service on an Ubuntu box rather than a considered design decision. The whole plugin was just an experiment!

You could probably take out the systemd references and run it as a standalone daemon in a container. Good luck!
